name: xtime-dev
channels:
  - conda-forge
dependencies:
  - cftime
  - codecov
  - pip
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-sugar
  - pytest-xdist
  - xarray
  - scipy
  - pip:
      - pytest-circleci-parallelized
